### ISSUE TITLE
Duplicate Subtitle Found 

### ISSUE THREAD

**Issue by topleague** [benhuson/wp-subtitle#23]
I used this plugin and then deactivated it. Used another plugin. But I can see that your plugin shows the sub-title at a new location - a duplicate version of the sub-title. Ok, here's a screenshot for your reference. 
![khurda cuttack among diabetes hotspots in country](https://cloud.githubusercontent.com/assets/10867370/18657036/16e17f76-7f14-11e6-8794-358a7f27ec21.jpeg)

I have tried deleting the custom field it created so I could make it disappear from below the header, but it hasn't worked at all.

**Comment by benhuson** [comment]
Hi, thanks for your report.

I am unable to produce that issue on my development sites.

I would need to see how you added the subtitle functions to your templates in order to figure out wether maybe it's an incompatibility with theme or the way it has been added to the theme.

Are you able to provide any of those details?

Ben

**Comment by topleague** [comment]
Thanks for your reply! I've added the code <?php the_subtitle(); ?> below the H1 as in Single.php (I'm using the Flex Mag WordPress theme). Here's the screenshot: http://www.awesomescreenshot.com/image/1613224/ace3065deeed91acd872d2b547ea082c

Let me know if I'm doing anything wrong. 

The problem is after uninstalling your plugin, I'm unable to use an alternative plugin successfully because (as per the screenshot shared previously) your plugin creating a duplicate title and subtitle above the site header. I tried several other plugins, but it still interferes with them. 

Please, advise!

Thanks,

**Comment by topleague** [comment]
Hello Ben,

Did you get a chance to look into my request?

Cheers,

*Susanta Sahoo*
(Founder & CEO, Top League Technologies)
Email: susanta@topleaguetech.com
Website: http://topleaguetech.com/

**Comment by benhuson** [comment]
So you installed my plugin first.

Does the issue happen when my plugin is active?

Or is it when you have used my plugin, then disable it and activate a different subtitle plugin? If so which plugin?

Thanks

**Comment by topleague** [comment]
Thanks for your reply. Here's the sequence of the events:

#1: I installed your plugin on my site and then see there is an instruction
to add a line of code in order to make the sub-heading appear on my posts.
I try to find where to add it but fail.

#2: Then I deactivate and uninstall the plugin, and try installing and
activating this plugin
<https://wptavern.com/new-plugin-adds-subtitles-to-wordpress-posts-pages-and-custom-post-types>
and
it works out of the box. However, I notice that a pair of duplicate heading
and sub-heading also appears above the header menu (ref:screenshot in
my previous email).

#3: I suspect the previous plugin leaves something behind causing this
issue - I try deactivating/deleting the current plugin and using one more
subtitle plugin but it issues refused to go away. I suspect the first
plugin (wp subtitle) may have caused the issue to appear.

#4: I go to your faq tab <https://wordpress.org/plugins/wp-subtitle/faq/>
and see that it says subtitles are stored as meta data and it won't be
removed automatically. I try to remove the box and save my post to see this
has resolved the issue but this doesn't. :-(

#5: At this point, I'm helpless because I can't really use any subtitle
plugin because if I do, it brings the weird issue back. Then I decide to
use only your plugin to see if I can add the line of code and make it work.

#6: I search Google and find a blog post that says I should add the line of
code under the <h1></h2> in the single.php. I do that but it still doesn't
seem to resolve the issue.

#7: I decide to contact you via github so you could take a look at it and
put an end to my misery :-)

Hope this helps.

*Susanta Sahoo*
(Founder & CEO, Top League Technologies)
Email: susanta@topleaguetech.com
Website: http://topleaguetech.com/

**Comment by benhuson** [comment]
Thank you for the in-depth response.

That plugin stores and access the subtitle data as a different meta field, so as long as the WP Subtitle plugin is disabled they should not interfere with each other.

This leads me to think that it is perhaps an issue with subtitle plugins that try to automatically output the subtitle, and your theme.

Have you tried a default Wordpress theme to see if the issue persists when using the Subtitles plugin?

Also maybe check this issue with the Subtitle plugin which could perhaps be related: https://github.com/professionalthemes/Subtitles/issues/81

If you view the HTML source of the page, can you see where that duplicate subtitle is being outputted? Is it near the `<title>` tag?

**Comment by benhuson** [comment]
Closing due to no further feedback
