### ISSUE TITLE
Getting subtitle for Posts page.

### ISSUE THREAD

**Issue by michaellindahl** [benhuson/wp-subtitle#33]
I'm unable to display the subtitle for the page that is specified to show the latest posts. I cannot use `the_subtitle()` as I'm not in within The Loop, nor am I able to find the page ID to use the other method `get_the_subtitle()`. I'm looking for something like the `single_post_title` that is being used to display the title. (e.g. `twentyseventeen/index.php:23`)

**Comment by benhuson** [comment]
You may be able to get the ID of the posts index page using the following:

`$id = get_option( 'page_for_posts' );
get_the_subtitle( $id );`

**Comment by michaellindahl** [comment]
Thanks for the quick solution!

Although this accomplishes the task, I worry that there could be cases where it doesn't grab the correct subtitle. I'm not an experienced Wordpress developer (yet). Here's what I've got in the `index.php` borrowed heavily from `twentyseventeen`. I'm worried the first case could be a page that isn't the `page_for_posts`. It looks good thus far, and I'll update this issue if I find a case where this doesn't work. 

```
<?php if ( is_home() && ! is_front_page() ) : ?>
	<header class="major special">
		<h2><?php single_post_title(); ?></h2>
		<p><?php 
		if (function_exists('the_subtitle')) { 
			echo get_the_subtitle( get_option( 'page_for_posts' ) ); 
		} else { 
			echo get_bloginfo('name').' '.get_bloginfo('description');
		} ?></p>
	</header>
<?php else : ?>
	<header class="major special">
		<h2>Posts</h2>
		<p><?php echo get_bloginfo('name').' '.get_bloginfo('description'); ?></p>
	</header>
<?php endif; ?>
```

**Comment by benhuson** [comment]
`is_home()` checks you are showing the main posts archive, wether that's by default on the homepage (no page assigned) or on a specific page set by `page_for_posts`.

`is_front_page()` checks you are on the home page.

So I think `is_home() && ! is_front_page()` should work 😄 - is showing blog archive and not the home page means a `page_for_posts` must be assigned

**Comment by michaellindahl** [comment]
Awesome, thanks for the detailed explanation!
