### ISSUE TITLE
Change the title "Subtitle" in post list table

### ISSUE THREAD

**Issue by AleCss81** [benhuson/wp-subtitle#39]
Hi, I would like to have the same title that I have set with `my_wps_meta_box_title` function also in post list heading table. Below exactly where I mean.

![image](https://user-images.githubusercontent.com/5421829/51472530-06deef80-1d7a-11e9-9b12-c995d54753f0.png)

In particoular, I've needed for a custom post type.

Thank you very much

**Comment by benhuson** [comment]
This will be fixed in the next release:

https://github.com/benhuson/wp-subtitle/commit/35e6b3409b0f72e17eb69b4945798612b2cf2470
