### ISSUE TITLE
Translation does not work (wrong domain identifier)

### ISSUE THREAD

**Issue by davidspiess** [benhuson/wp-subtitle#8]
The `TEXTDOMAIN` constant in `wp-subtitle.php` has to point to `wp-subtitle` instead of `wps_subtitle`.
You should also consider passing the domain string directly to the __ method instead of using a constant.

See
https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/
http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/

**Comment by benhuson** [comment]
Thanks for pointing that out - I hadn't twigged that that would cause an issue for other parsers.

**Comment by davidspiess** [comment]
It isn't a big issue :)

**Comment by benhuson** [comment]
Fixed in https://github.com/benhuson/wp-subtitle/commit/805a5bd3c6fdf0cee0876fc172519a5cd94b92dc

**Comment by hatsumatsu** [comment]
Is this fix available via the Plugin Directory / one click update? That would be great! :)

**Comment by benhuson** [comment]
Now added to the plugin directory as version 1.5 so should be available shortly.
